version: "3.8"
services:
  mysql:
    image: gms/mysql
    build:
      context: ..
      dockerfile: docker/mysql.dockerfile
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_DATABASE:
    restart: unless-stopped
    expose:
      - "3306"
    volumes:
      - "mysql:/var/lib/mysql/"
      
  backend:
    image: gms/backend
    environment:
      ENV: DEV
    build:
      context: ..
      dockerfile: docker/backend.dockerfile
    tty: true
    restart: unless-stopped
    depends_on:
      - mysql
    expose:
      - "8080"
  
  nginx:
    image: gms/nginx
    build:
      context: ..
      dockerfile: docker/nginx.dockerfile
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"

volumes:
  mysql:
